# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_myreportnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreportnew',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='EmailNew'),
        ),
    ]
