# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_myreportnew_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriousBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charDocument', models.CharField(max_length=15, verbose_name='DocumentNr')),
                ('dateExecute', models.DateField(auto_now=True, verbose_name='ExecuteDate')),
                ('charPayer', models.CharField(max_length=50, verbose_name='PayerName')),
                ('charPayerReg', models.CharField(max_length=20, verbose_name='PayerRegNr')),
                ('charPayerAccount', models.CharField(max_length=25, verbose_name='PayerAccountNr')),
                ('charPayerBank', models.CharField(max_length=10, verbose_name='PayerBankSWIFT')),
                ('charReceiver', models.CharField(max_length=50, verbose_name='ReceiverName')),
                ('charReceiverAccount', models.CharField(max_length=25, verbose_name='ReceiverAccountNr')),
                ('charReceiverBank', models.CharField(max_length=10, verbose_name='ReceiverBankSWIFT')),
                ('charReceiverReg', models.CharField(max_length=20, verbose_name='ReceiverRegNr')),
                ('floatSum', models.FloatField(verbose_name='Sum')),
                ('charAim', models.CharField(max_length=250, verbose_name='PaymentAim')),
                ('floatCost', models.FloatField(verbose_name='ServiceCost')),
            ],
        ),
    ]
