# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0004_seriousbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriousbank',
            name='dateExecute',
            field=models.DateField(verbose_name='ExecuteDate'),
        ),
    ]
